name: learnsmart
description: "A new Flutter project with accessibility features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^22.1.37
  provider: ^6.0.5
  string_similarity: ^2.0.0
  flutter_svg: ^2.0.10+1
  flutter_tts: ^3.5.0
  http: ^1.2.2
  video_player: ^2.2.10  # For video playback
  path_provider: ^2.0.11  # For accessing file storage
  google_fonts: ^5.1.0  # To include dynamic Google fonts (if needed)
  uuid: ^4.5.1  # For generating unique IDs
  firebase_core: ^3.2.0  # Firebase core integration
  firebase_auth: ^5.1.2  # Firebase authentication
  cloud_firestore: ^5.1.0  # Firestore database integration
  image_picker: ^1.0.0  # For image selection
  permission_handler: ^11.0.1  # For managing runtime permissions
  firebase_storage: ^12.0.0  # For Firebase file storage
  audioplayers: ^6.1.0

dev_dependencies:
  flutterfire_cli: ^1.0.1-dev.2  # Firebase CLI integration
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # For linting and code analysis

flutter:
  uses-material-design: true

  # Asset directories
  assets:
    - assets/fonts/  # Fonts directory
    - assets/vectors/  # Vectors directory for SVGs
    - assets/images/  # Images directory

  # Adding custom fonts
  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
        - asset: assets/fonts/OpenDyslexic-Italic.otf
        - asset: assets/fonts/OpenDyslexic-Bold-Italic.otf
    
